/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hellojni_Hello */

#ifndef _Included_com_hellojni_Hello
#define _Included_com_hellojni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hellojni_Hello
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hellojni_Hello_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
